### ISSUE TITLE
What's the "A" field's encoding?

### ISSUE THREAD

**Issue by rtomayko** [Bittrex/beta#1]
I'm trying to follow https://github.com/Bittrex/beta/blob/master/README.md#queryexchangestate in a node.js environment and see messages like:

```json
{"H":"C2","M":"uE","A":["q1byVbJScgpx1vUJclbSUfJTsjI0Nraw1FGKUrKKrlYKiVSyMtBRCgKSegZAYGpobqSjFKhkZWpoYGQGFgKBWh2IUkMUpWbmYKVAbm2sjlIw0EAglQaiagE="]}
{"H":"C2","M":"uE","A":["ZYyxDsIwDET/5WYT2Y7TJB5hQB2oBO0CqCs/UeXfCR0QEjecdLqnt+ECx3E5HcbzNM4gTHBh00J4wJ8bljucCbfegXuEayRc4TWbBRWLWbO2lTB/efnlRXjn+2z071NJtv+iQ0g1Dqlo+eheXbe2Nw=="]}
```

The arguments (A) field looks to be base64 encoded but decoding leads to a non-identifiable filetype. What's A encoded as?

**Comment by pdotmidge** [comment]
The base64 decodes to gzip data, which when decompressed yields exchange state data:
```
{"M":"BTC-LRC","N":13389,"Z":[{"TY":0,"R":0.00005172,"Q":51026.00000000},{"TY":1,"R":0.00005167,"Q":0.0}],"S":[],"f":[]}
```
I'm guessing we overlooked this because we opted to use non-minified examples instead of what you'd see over the wire. So you must b64-decode then decompress the first element of array-valued keys before calling `JSON.parse()`.

I'm going to leave this open while I review the hub response code.

**Comment by pdotmidge** [comment]
This doesn't repro in the C# sample posted to the docs repo, but I see what's happening. The C# example invokes the subscription callback with the value of `A`, your NodeJS SignalR library appears to be passing you the raw SignalR frame.

If you decode `A` as defined in [Response Handling](https://github.com/Bittrex/beta/blob/master/README.md#response-handling) and pass the resulting data to your handler, you should be fine.

Reopen if this doesn't resolve things for you.

**Comment by rtomayko** [comment]
Cool. Will give it a go later today and let you know what I find. Thanks @pdotmidge.

**Comment by rtomayko** [comment]
Yep, looks like I was just using the wrong decompression algorithm. Switched from gzip to to inflate with no header and everything is looking great. For nodejs, you want `zlib.InflateRaw`. Thanks again!

**Comment by n0mad01** [comment]
i've added a working sample as a pull request here:
https://github.com/Bittrex/beta/pull/5

you can also checkout the gist:
https://gist.github.com/n0mad01/6a582e803ab03c517841180a1844aecf

i hope this helps!
