### ISSUE TITLE
PHP client example

### ISSUE THREAD

**Issue by marcelmolenaar** [Bittrex/beta#12]
I would be very happy if you could provide a PHP client example as well in here. I am trying for days now with this client ( https://github.com/marcelmolenaar/php-signalr-client ) but can't get it to work and i issued a post on stackoverflow about it: https://stackoverflow.com/questions/49754714/subscribe-to-signalr-websocket-method

**Comment by pwnzya** [comment]
Hello @marcelmolenaar :)

You might be able to find some sample code in one of the PHPwrappers for Bittrex API found in [here](https://github.com/search?l=PHP&p=1&q=bittrex+api&type=Repositories).  
Look for ones that have implementation for the websocket part of the API.

Note that they might not have been updated yet to meet the specification of the new Bittrex Beta API.
In that case, you have to make some changes yourself to the sample code, but I am sure you can get a good idea on how to "subscribe" to the websocket endpoints.

Good luck.

**Comment by marcelmolenaar** [comment]
Thank you soooo much for this!!! You made my day!!!
