### ISSUE TITLE
Explanation payload when calling method

### ISSUE THREAD

**Issue by marcelmolenaar** [Bittrex/beta#16]
Is there any explanation or example about the payload to send when calling methods? I mean an explanation about the A: M: H: R: I: keys and such. 

Regards,

Marcel

**Comment by bittrex-ben** [comment]
Please see docs on https://github.com/Bittrex/beta, specifically the appendix that provides the definition of the minified variables.   If you have a more specific question please let us know.

**Comment by marcelmolenaar** [comment]
Thank you!
