### ISSUE TITLE
Trade IDs in SubscribeToExchangeDeltas websocket updates

### ISSUE THREAD

**Issue by rtomayko** [Bittrex/beta#2]
We're up and running on the websocket beta channel and things are looking good. Kudos to the team. 

One thing we'd really like to see added to the websocket interface is unique IDs for each fill in SubscribeToExchangeDeltas messages. The REST API getmarkethistory endpoint has unique ids but we'd like to avoid polling.

Not sure if this is the appropriate channel for feature requests but wanted to get something in while the beta is in progress.

**Comment by gungorkdr** [comment]
I agree with Mr. Tomayko, adding unique IDs to SubscribeToExchangeDeltas messages would be very useful.

**Comment by pdotmidge** [comment]
@rtomayko good to hear!

The REST and WS API are fed from the same internal source, the ID just isn't plumbed through on the WS side.

I can't promise anything, but I'll leave this issue open and look into it.

**Comment by pdotmidge** [comment]
This is now fixed in the beta and the docs are updated. The new field is `FI` / `FillId`.

**Comment by rtomayko** [comment]
Beautiful. Thanks @pdotmidge!
