### ISSUE TITLE
Historical data (GetTicks) from a certain period

### ISSUE THREAD

**Issue by miguemau** [Bittrex/beta#20]
Hello! I sent in a support ticket for this but I figured this might be just as good for your team to review. 

I have a suggestion that would make a feature from the 2.0 API much more powerful and easy to maneuver. For the GetTicks function, for example:
https://bittrex.com/Api/v2.0/pub/market/GetTicks?marketName=BTC-ltc&tickInterval=onemin

There are too much entries and data that is incoming when the API request is called. I tried to look if there existed some way of just receiving the latest X entries, or even set a start time to look at entries from that start time. I found some links used had this &startTime=TIMESTAMPNUMBER but modifying this doesn't change the results (same results with different Unix timestamp in URL). So I would like to know if such option to filter entries exists or if it can be implemented.

I know of GetLatestTick but that displays the most recent, but I have noticed that in the oneMin interval the system submits 2 entries every 2 minutes. For example at 11:00 it will submit 10:56 and 10:57 but not 10:58 until it is 11:02 then it submits 10:58 and 10:59, so one of them doesn't appear as the latest, it will skip over one.

**Comment by pdotmidge** [comment]
Thanks for the suggestion, it's noted. However, be advised that the 2.0 API is neither supported nor documented by Bittrex, and any information or libraries you may find that deals with it is not endorsed or supported by us and you use it at your own risk.
