### ISSUE TITLE
Cloudflare... wtf?

### ISSUE THREAD

**Issue by technicalviking** [Bittrex/beta#22]
Trying to connect a websocket to the https://beta.bittrex.com endpoint per the documentation has suddenly become impossible for me...  because I'm running face first into cloudflare protection on that endpoint.

I'm noticing that other libraries have attempted to implement mechanisms to bypass this, but it would really be appreciated if you could get eliminate the cloudflare protection from this endpoint.

EDIT:  

I managed to implement a (somewhat functional) cloudflare bypass to get around the challenge (all credit for updated bypass goes to https://github.com/zoh/go-cloudflare-scraper, because of his updates to Parse) to his updates) and then cloudflare throws a fucking recapcha?   

If you want us to switch to poloniex or something, just tell us!

**Comment by knap1930** [comment]
Seriously Bittrex?!?!

**Comment by knap1930** [comment]
looks like cloudflare is disabled again.

Bittrex, is this going to be a thing? or was this an accident?

**Comment by pdotmidge** [comment]
this was a mistake. one of our team cleaned up our cloudflare rules. i've put it back on a temporary basis. once we drop CF on the production socket endpoint (socket.bittrex.com) the beta endpoint will be turned off.

are either of you in #api-developers in the bittrex slack? that's likely the best place to get advance notice of this happening.

**Comment by djmarcin** [comment]
How do we access the bittrex slack? It would be great to know when that
switch is going to happen ahead of time.

**Comment by technicalviking** [comment]
I didnt even know there WAS a bittrex slack channel.  Not surprising given
that the most recent relevant documentation about it is from a 6 month old
post on the support site, indicating the channel access is by invite only,
and will one day be automated...

Is there an assumption in your office that the slack channel was
ubiquitously known and accessible?

**Comment by pdotmidge** [comment]
bittrex.slack.com - let me know if you have issues signing up. Slack has limits on the number of users in a public instance, and occasionally disable signup.

**Comment by knap1930** [comment]
would love an invite as well

**Comment by pdotmidge** [comment]
i need an email address in order to invite someone to slack. if you're unwilling to provide it here, we'll figure something else out. for obvious reasons i'm not going to publish my incredibly difficult to guess email address.

**Comment by knap1930** [comment]
knap1930 AT gmail.com

**Comment by pdotmidge** [comment]
Looks like everyone got in.

**Comment by pwnzya** [comment]
I would like an invite as well. Thanks.

**Comment by changneng** [comment]
I would like an invite as well. Thanks.

**Comment by JKorf** [comment]
I'd like an invite aswel

**Comment by dmitrig89** [comment]
Can I please get an invite as well? Thanks

**Comment by apobekiaris** [comment]
Can you invite me also?

**Comment by pltchuong** [comment]
Can I get invited pls?

**Comment by michaelc9** [comment]
I would like an invite to the slack channel as well!
