### ISSUE TITLE
queryExchangeState still returns empty MarketName

### ISSUE THREAD

**Issue by slazarov** [Bittrex/beta#6]
Invoking 'queryExchangeState' still returns empty MarketName, e,g:
```
    {
        'M': None,
        'N': 33218,
        'Z': [],
        'S': [],
        'Fills': []
    }
```
It would be helpful to add it in the case of multi-threaded invokes.

> https://github.com/slazarov/python-bittrex-websocket

**Comment by slazarov** [comment]
I would like to clarify that there is a workaround for that. When you are invoking, your message should look like this:

```python
    def invoke(self, method, *data):
        message = {
            'H': self.name,
            'M': method,
            'A': data,
            'I': self.__connection.increment_send_counter()
        }
        self.__connection.send(message)
```
so when you receive the message from the socket, it should have an identical `I` as from the method above. In the case of multiple signalr client instances what users should do is to track the invoke numbers and when creating a new instance of their signalr client they would have to modify the initial increment number.

**Comment by pdotmidge** [comment]
When testing with the BTC-ETH market I see the following:

```
4/8/2018 11:38:06 PM - {"M":"BTC-ETH","N":29893,"Z":[],"S":[{"TY":1,"R":0.05868880,"Q":0.0},{"TY":0,"R":0.05869609,"Q":28.92000000}],"f":[]}
```

Can you tell me which market(s) you see this with?

Please make sure you're testing against `https://beta.bittrex.com/signalr` and you are attaching to hub `c2`.

**Comment by slazarov** [comment]
@pdotmidge this is the output from `SubscribeToExchangeDeltas`. I am specifically discussing `QueryExchangeState`.

**Comment by pdotmidge** [comment]
So you are, and so we're omitting the market name. We'll take a look.

**Comment by pdotmidge** [comment]
The `MarketName` value was inadvertently omitted when generating the JSON payload, we have fixed this internally and the update will deploy by the time we end the beta and go to general release. Please reopen if you still see this after the beta ends.

**Comment by slazarov** [comment]
@pdotmidge I am confirming that the invoke provides the market name.

**Comment by jblaszak** [comment]
Re-opening - the invoke no longer provides the market name.

**Comment by pdotmidge** [comment]
On beta.bittrex.com or socket.bittrex.com. If on socket, known issue and fixed but not yet deployed.

________________________________

**Comment by jblaszak** [comment]
On socket.  Forgot I quickly changed from beta to socket as the last thing I did before leaving it for a few days.  Thought something was up with the service.  Thanks for the quick response!

**Comment by pdotmidge** [comment]
No problem.

________________________________
