### ISSUE TITLE
python - incorrect gzip header

### ISSUE THREAD

**Issue by algpet** [Bittrex/beta#8]
after decoding input string with 
mybytes = base64.b64decode(recieved_string)

I am trying to ungzip this data using python's gzip library
gzip.decompress(decoded_bytes)

this always leads to 
OSError: Not a gzipped file (b'}\\')

what I am doing wrong ?

**Comment by slazarov** [comment]
Check [PR 7](https://github.com/Bittrex/beta/pull/7) for info.

**Comment by pdotmidge** [comment]
for posterity - gzip libraries tend to expect file-based content. here a deflate library produces the expected result as it just works on a compressed chunk of data. we will update the docs to make this clear. sorry for your wasted time.
